apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-notification-consumer
spec:
  selector:
    matchLabels:
      app: push-notification-consumer
  template:
    metadata:
      labels:
        app: push-notification-consumer
    spec:
      containers:
      - name: push-notification-consumer
        image: synthiatelemed.azurecr.io/push-notification-consumer:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "30m"
