apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-mock-depl
  namespace: hospital-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-mock-depl
  template:
    metadata:
      labels:
        app: hospital-mock-depl
    spec:
      containers:
        - name: hospital-mock-depl
          image: CONTAINER_REPO/hospital-it-system-mock
          resources:
            limits:
              memory: "256Mi"
              cpu: "150m"
            requests:
              memory: "100Mi"
              cpu: "10m"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: hospital-mock-secret
                optional: false
            - configMapRef:
                name: hospital-mock-configmap
                optional: false
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
