apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-mock-depl
  namespace: hospital-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-mock-depl
  template:
    metadata:
      labels:
        app: hospital-mock-depl
    spec:
      containers:
        - name: hospital-mock-depl
          image: synthiatelemed.azurecr.io/hospital-it-system-mock:f3ee98ff64894305691239cfb6542a848a73b2a2
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "20m"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: hospital-mock-secret
                optional: false
