apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-mock-depl
  namespace: hospital-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-mock-depl
  template:
    metadata:
      labels:
        app: hospital-mock-depl
    spec:
      containers:
      - name: hospital-mock-depl
        image: synthiatelemed.azurecr.io/hospital-it-system-mock:52e7f529bb8015db44b3321cc36eb3565a2c51ef
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "20m"
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: hospital-mock-secret
              optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-mock-srv
  namespace: hospital-mock
spec:
  selector:
    app: hospital-mock-depl
  ports:
  - port: 3000
    targetPort: 3000
