apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hospital-mock-secret
  namespace: hospital-mock
spec:
  encryptedData:
    DATABASE_URL: AgBOqvfz4Yt0jGSvsE4eChnbAQI/t3bjVH3qZ5kxxDZLzwzuSTXGTOD9suus8staXRkqbLE5d/xFrSY6WajG9N5DAEbHYfaQ8mfxxOZGD6DXmJiYnHHX9GSgVaNMIJQASl8U4Qh2Io2gFrVxGzC3mj1EmywdcwO/RyNktoddeM/P43/nP1mCRLKksHHrSyNl6K2rppWmK405IFW6QwSE3M/62EMKsLJ1aVREZ+AgmwMGS/VNZv/Vd8j4YBG8F/csct91UK4HCfg+AJNBAM1sJ25XRTaHa+d1Ec47zx0WujWctg1kddsi595BJuYAJTQWxUG2/mTgFce+dKSVkPRxjDymPfu3T8QMfMGwnIrUQCdNJJN22gkIKZCMgkAxkNO4vwWDtF8cFPQIrcYBOz56nRip8o5npNCvYZF4LNDl6dNr951x9k+hR4i8VgWiFSErP3FjwlyYQ6a2uctFOB/ui/uN4SvuP+5SlM6sGq8m8TtY/s/1puh/q7aEbyUCxVQ5TIj2XER/202qNep2LtuBcyhCjv3wz1uowl+dPAnyhuxQrl2Kw154kPKmx/asSbfvk9cud5KL1zboDplMGd3xZ0NamECHTnaBzXQOulaBOhM0EBJTsDa1JjQg+RW/t86bU6ajEeYQ/lemeQMT7uZhTUjEW0dQe+1LbIvgF88Dkq7JbMVwxd1Zk1eiLFnc6RXTfI1Vmr9e2UX/efcr1MdzbPMEmtO3ofC6GwjDDWKHj0euf+hWB5g3So0amXo8AXEuZVYdZXnIIlQyJGahSVHB9MJfy64YQCVlRZ7+jH+KmTz8npDdLKH0Oly7h3CwEo77bCydKxRmonadCDS/HHeXo1A3p2JGewvu/dnyGDrCNcQi/c08BCvrERWdfg==
    RABBITMQ_URL: AgAp8pIHtq03tWgBj3wA1xvSgApGigAS9X2B/VDnmTwtD2ZjnvD64IWymOPWIji0kigY2byCmL2lyXUj4aJa2+6l8OUN5BSdMpM2A6AOJkoOqkpA7QabuT3KycvIHqr8Obv0CyB2+wrj3rbytKf3xKh0kke4i6lo4N+eM6yt7mK2uV9Lo0As14TRu7XzAfNvItuaZcZ70qj9z3zI5vff2vuy0CqDgEW/nkG6F+Opuz/jIYv2R1Sc0aiE6U/ese2XP608YlgCjQOpy0XFSq23iQ3c45tBSv48CwUO48D0KSBqNAjr/wFr3vJg4aeFpKlBXzzLoLl36sdYTLl3hr64GvHPmNBvZzoZpev00Zz8c5JlkvuGX6/ccmBdNQvt0pwXqwhEGrQONe8fYAbtO1YeUckzXdUtT/MDAneZvmlhS2LRv7TaCBhXKwEe19pU/NUzMqj+d3VbeqAo03czDytOuF48WR8F9yFfiq2meleaiaembBTEuKf0nGgcrC7OugLPsrnAI/Y5FvJFkvykTC/8pzkp/gZvuxLkcC5n0Lt0DR7d3ojAcBHJdE7oMs5Fa0+A7uXzVNm4S8f2YfOHHg3UmeVXnR40I+wLNC+ZHyzx/hyb7Kgt/eJfPiPTBTDmuqaUtGwA99FIQvY7jRieH58Sik8ndXSm/N7c1mmmfAeg3PqUzDeeqGuFx0vin8UYukpmK1wOk3GbJMRX5IQ2zf6LYzmPOFr83mLpgufldxtirXVifiMLUQjzQvUCuaD3qruMNZlVgeqW/QmIIph6iPU1wgOm/yvG6035irVHnFG/qAWlQv4E9yP51dvLHDbK1pg0TCcClg4=
  template:
    metadata:
      creationTimestamp: null
      name: hospital-mock-secret
      namespace: hospital-mock
    type: Opaque

