apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hospital-mock-secret
  namespace: hospital-mock
spec:
  encryptedData:
    DATABASE_URL: AgAYPi5zCccUxRPH/ZFpcSM/LpqkymR0vX0TvRcoNTHAH2/qrhzIHK7ExE6qK2iZHghPy7C2BwIz63WNWpEvu4NZ3+jgnogglPV2HVeFj1wGDREmnCTHLK5pUT0kw52thsewZmVcDyTFduW6Ci63HQxWm4U+2p0JU16U9/2zqbY5Fcw2PaEInuPbHR8FvvfVK8WnSBvpoQQCq7PX9y9RBjO/wmkkDYV7q9GBaKBUjf6yeZdkWE5mXvSwAR+FF8JSOllc6CowrOpJvYJGA2xE0tQwWP125wKD67jufRxMI4bHQwIv4vMJaTWUtc8g0jNrNtl13l8E03InnQzjOfc08+Voh5gcGfWaDwV0IgCHkTS+oO+JfyP4B000lTJvmgP77cFSzB+zXESuuPeFP5JJ5/nrS3cM+b6o94/1XKMW/A2/S7xXVMAdimP1bV6ZJIJ/K6fhKQbZDHMZbBiuwpMrAGuyfY8RzvQtIfmS8nh66EvyVF+BipdImU7xErq6gwlSr1OFYQvE+d6ElbAtirfUrTBR0bp+uZ/4gdZPaaTCUuogwmragTvc0ZQKfkdr3B6SuTgZPHi3YV6PZvcALiKwxm4n/kcC5U8T9x3xTY3dVIushJ1bbjbGMY4cLwdpC6XY3gzlgVDb276Ysj02F1hjWiXyioCpQUzKtMTIv/iJAu5wazU98dku1J/VOfkqdcKR+p30CHdEAfpV9Mu6uw+xOqkK7ELVamKrY2IhZjpgyKXCklpJohfSZVQFPTkD8/uqgXSwN5q2H0pO5b01n1bO54t3BaaekZUlrNx/QBVuM8pqXVOhdTVL1uFLekfyZDKhelkaJjlWMBfSTfBggjP04OVWqGrNRRI3T/iv/gkgKNn4SDOIp/O9nDZ3KUVzlodezYMjjNssnIzjkoeZhXDKlw==
    RABBITMQ_URL: AgBaWX012fi78Pd7sa/9c07FD73MppCgvdQ9Tj5KyP2jyjg1IOckwKO8OedX1UbrUBM2Y68n/jtHnyoMid6aJYl9iZb+kGlkdxrLb53hYAZIY+d1isovjpPKcaOywpD+DlPKQOB7jnmi111EFl+oW46NBlt/WT3L+ZC/Mu+Q6YsN7RXeRY5TM+wHVFvqkBuANAWjPHceHl2ynU4DyqTgAI4EHvHklmwKGIEV9QxAC//gVjcn7TvkKd9/4qkw6CmXdrW79unKPXTs0JLYb4RpLISeuTOLyuHXmT5RA0/jk4u1TSQ95onoeiVarALTgTX9Xug2APBctCUG5FR6cPZv8i2lFlIvDbcbJdUZherr3B0dRByGME5GRXCtp/ec2ooQHlgqizJB95Lyz6Bf+aCPZWCE/6ijjS07G9kWwHky79e4vQLhFIPQE1FwBmtxVHg7KAcB5iJFr3REw7kfoFMp2WFaVd1SqllQ/pePRPgHS89DXx6YD+CA8KQDkp0x8W7J15BpWd7kN+1U6YXo7tgmk0ndAIJA+cLcjjSonDYk0WUCcz7AC+qJ+5AoOkLOwtxBZUgo5/zeI9ubHtvMXxIVW0tJPTxs/2G3Sz7QlHYSm1VMxtzzIu7iWe56NzeB68tn2ZNQN4y1/NWIVhquALeEPFWurmZkf+cSJwmS6g0u6uaazEwM3hTWiTU4U1CuOJZ8t7DBXL3RHYiDTNnELQe9Gyjhy1TskCXF0i6SxdqNy84X5gRBsQCiD2lv/eEMSA1189q6DCW5CWOwjhJKPw7YIbhvvHxxzkrYstE+PCSuWhxoh+MwoVx0Z7/3r0kNOrEB0RtSL5U=
  template:
    metadata:
      creationTimestamp: null
      name: hospital-mock-secret
      namespace: hospital-mock
    type: Opaque

