apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-api-configmap
  namespace: backend-api
data:
  TOKEN_SERVICE_HOST: heimdall-grpc-srv
  MODE: production
  PORT: "8080"
  GIN_MODE: release
  HOSPITAL_SYS_ENDPOINT: "http://hospital-mock-srv.hospital-mock:3000/graphql"
  TOKEN_SERVICE_ENDPOINT: "http://heimdall-grpc-srv.heimdall:5050"
  # DB
  DATABASE_NAME: synthia
  DATABASE_SSL_MODE: verify-full
  DATABASE_SSL_ROOT_CERT: /app/DigiCertGlobalRootCA.crt.pem
  DATABASE_TIMEZONE: Asia/Bangkok
  # Redis
  REDIS_HOST: common-redis-srv.default:6379
