apiVersion: apps/v1
kind: Deployment
metadata:
  name: measurement-result-api-depl
  namespace: backend-api
spec:
  selector:
    matchLabels:
      app: measurement-result-api-depl
  template:
    metadata:
      labels:
        app: measurement-result-api-depl
    spec:
      containers:
        - name: measurement-result-api-depl
          image: synthiatelemed.azurecr.io/measurement-result-api:1a83e27be99a58384eeea416d0df6ab86960f7d3
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: 10m
              memory: "80Mi"
          envFrom:
            - secretRef:
                name: measurement-result-api-secret
          env:
            - name: HOSPITAL_SYSTEM_ENDPOINT
              value: http://hospital-mock-srv.hospital-mock:3000/graphql
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
