apiVersion: apps/v1
kind: Deployment
metadata:
  name: measurement-result-api-depl
  namespace: backend-api
spec:
  selector:
    matchLabels:
      app: measurement-result-api-depl
  template:
    metadata:
      labels:
        app: measurement-result-api-depl
    spec:
      containers:
        - name: measurement-result-api-depl
          image: synthiatelemed.azurecr.io/measurement-result-api:0fed80b74187fc3f3d52bb31615956cbed9e398d
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: 10m
              memory: "80Mi"
          envFrom:
            - secretRef:
                name: measurement-result-api-secret
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
