services:
  postgres:
    image: "postgres:13-alpine"
    volumes:
      - "./hospital-mock-test.sql:/docker-entrypoint-initdb.d/hospital-mock-test.sql"
    environment:
      POSTGRES_PASSWORD: "unsecurepassword"
    expose:
      - "5432"
#    ports:
#      - "5432:5432"
  hospital-sys:
      image: "synthiatelemed.azurecr.io/hospital-it-system-mock:latest"
      pull_policy: always
      environment:
        DATABASE_URL: "postgres://postgres:unsecurepassword@postgres:5432/hospital-mock"
        RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
        RABBITMQ_EXCHANGE_NAME: "notification"
        RABBITMQ_ROUTING_KEY: "push-notification"
      ports:
        - "30821:3000"
  rabbitmq:
    image: rabbitmq:3.11-alpine
    expose:
      - "5672"
