apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-notification-consumer
  namespace: rabbitmq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: push-notification-consumer
  template:
    metadata:
      labels:
        app: push-notification-consumer
    spec:
      volumes:
        - name: consumer-secret-vol
          secret:
            secretName: push-notification-files-secret
            optional: false
      containers:
        - name: push-notification-consumer
          image: synthiatelemed.azurecr.io/push-notification-consumer:beaa219384939b128581012df8e8c5ef8ed192d1
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "30m"
          volumeMounts:
            - name: consumer-secret-vol
              mountPath: /secret
              readOnly: true
          envFrom:
            - secretRef:
                name: push-notification-consumer-secret
                optional: false
            - configMapRef:
                name: push-notification-consumer-configmap
                optional: false
