apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-doctor-api-depl
  namespace: backend-api
spec:
  selector:
    matchLabels:
      app: backend-doctor-api-depl
  template:
    metadata:
      labels:
        app: backend-doctor-api-depl
    spec:
      containers:
        - name: backend-doctor-api-depl
          image: synthiatelemed.azurecr.io/backend-api:b93c2a0a1664714b87c2da648133d7a488d4125e
          command:
            - "/app/bin/doctor-api"
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "16Mi"
              cpu: "10m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-api-secret
            - secretRef:
                name: backend-doctor-api-secret
            - configMapRef:
                name: backend-api-configmap
            - configMapRef:
                name: backend-doctor-api-configmap
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
