// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/datastore/patient.go

// Package mock_datastore is a generated GoMock package.
package mock_datastore

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	datastore "github.com/synthia-telemed/backend-api/pkg/datastore"
)

// MockPatientDataStore is a mock of PatientDataStore interface.
type MockPatientDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockPatientDataStoreMockRecorder
}

// MockPatientDataStoreMockRecorder is the mock recorder for MockPatientDataStore.
type MockPatientDataStoreMockRecorder struct {
	mock *MockPatientDataStore
}

// NewMockPatientDataStore creates a new mock instance.
func NewMockPatientDataStore(ctrl *gomock.Controller) *MockPatientDataStore {
	mock := &MockPatientDataStore{ctrl: ctrl}
	mock.recorder = &MockPatientDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientDataStore) EXPECT() *MockPatientDataStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPatientDataStore) Create(patient *datastore.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPatientDataStoreMockRecorder) Create(patient interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPatientDataStore)(nil).Create), patient)
}

// FindByID mocks base method.
func (m *MockPatientDataStore) FindByID(id uint) (*datastore.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*datastore.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPatientDataStoreMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPatientDataStore)(nil).FindByID), id)
}

// FindByRefID mocks base method.
func (m *MockPatientDataStore) FindByRefID(refID string) (*datastore.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRefID", refID)
	ret0, _ := ret[0].(*datastore.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRefID indicates an expected call of FindByRefID.
func (mr *MockPatientDataStoreMockRecorder) FindByRefID(refID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRefID", reflect.TypeOf((*MockPatientDataStore)(nil).FindByRefID), refID)
}

// FindOrCreate mocks base method.
func (m *MockPatientDataStore) FindOrCreate(patient *datastore.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MockPatientDataStoreMockRecorder) FindOrCreate(patient interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MockPatientDataStore)(nil).FindOrCreate), patient)
}

// Save mocks base method.
func (m *MockPatientDataStore) Save(patient *datastore.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPatientDataStoreMockRecorder) Save(patient interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPatientDataStore)(nil).Save), patient)
}
