name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      GIN_MODE: release
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Install mockgen
      run: go install github.com/golang/mock/mockgen@v1.6.0
    - name: Get Ginkgo
      run: go get github.com/onsi/ginkgo/v2/ginkgo
    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo
    - name: mockgen
      run: make mockgen
    - name: Run unit tests
      run: make unit-test
