apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-depl
  namespace: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall-depl
  template:
    metadata:
      labels:
        app: heimdall-depl
    spec:
      containers:
        - name: heimdall-depl
          image: synthiatelemed.azurecr.io/heimdall:ae476e1263b9299f9bbc63e0e7526095861c431b
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "32Mi"
              cpu: "10m"
          ports:
            - containerPort: 8080
            - containerPort: 5050
          env:
            - name: JWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: heimdall-secret
                  key: JWS_SECRET_KEY
                  optional: false
          envFrom:
            - secretRef:
                name: heimdall-secret
                optional: true
            - configMapRef:
                name: heimdall-configmap
                optional: true
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
