apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: common-headers-middleware
  namespace: default
spec:
  headers:
    frameDeny: true
    browserXssFilter: true
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
      - "DELETE"
    accessControlAllowOriginList:
      - "https://synthia.tech"
      - "http://localhost:3000"
      - "http://localhost:8080"
      - "https://dev.patient-frontend.pages.dev"
      - "https://doctor.synthia.tech"
      - "https://synthia-dev.loca.lt"
    accessControlAllowHeaders:
      - Content-Type
      - Authorization
    accessControlMaxAge: 100
    addVaryHeader: true