apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-redis
  template:
    metadata:
      labels:
        app: common-redis
    spec:
      containers:
      - name: common-redis
        image: redis:7
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
          requests:
            memory: "16Mi"
            cpu: "10m"
        ports:
        - containerPort: 6379
        
---
apiVersion: v1
kind: Service
metadata:
  name: common-redis-srv
spec:
  selector:
    app: common-redis
  ports:
  - port: 6379
    targetPort: 6379
