apiVersion: v1
kind: Secret
metadata:
  name: admin-basic-auth-user
  namespace: traefik
stringData:
  users: admin:$2y$10$ntkAiRDBJ3benX0i2fyMAeCF7U8NgAY3w1xmgeMKHWApb5VPx1rmK

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-basic-auth-middleware
  namespace: traefik
spec:
  basicAuth:
    secret: admin-basic-auth-user