apiVersion: v1
kind: Secret
metadata:
  name: admin-basic-auth-user
  namespace: traefik
stringData:
  users: admin:$2y$13$4LCNmbDerdZ7CvTfbQHp/u/q4TGUagiqvXHKGWCxavXvCcVpjKIbG

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-basic-auth-middleware
  namespace: traefik
spec:
  basicAuth:
    secret: admin-basic-auth-user