apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-frontend-depl
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: doctor-frontend-depl
  template:
    metadata:
      labels:
        app: doctor-frontend-depl
    spec:
      containers:
        - name: doctor-frontend-depl
          image: synthiatelemed.azurecr.io/doctor-frontend:cb19eec6b60ff537912a6fc3f18a660620cdc0b6
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "64Mi"
              cpu: "20m"
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_SOCKET_SERVER_ENDPOINT
              value: https://socket.synthia.tech
            - name: NEXT_PUBLIC_API_SERVER_ENDPOINT
              value: https://api.synthia.tech
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
