apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-frontend-depl
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: doctor-frontend-depl
  template:
    metadata:
      labels:
        app: doctor-frontend-depl
    spec:
      containers:
        - name: doctor-frontend-depl
          image: synthiatelemed.azurecr.io/doctor-frontend:5f5e9ba41a9562df9fe1e4431431e7105011390a
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "64Mi"
              cpu: "20m"
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_SOCKET_SERVER_ENDPOINT
              value: socket-server-srv.socket-server:3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
