apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: k8s/admin
    repoURL: ssh://git@github.com:synthia-telemed/infrastructure.git
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true