apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: frontend
    server: https://kubernetes.default.svc
  source:
    path: k8s/frontend
    repoURL: git@github.com:synthia-telemed/infrastructure.git
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true