apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rabbitmq-operator
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 3.1.1
    chart: rabbitmq-cluster-operator