apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: rabbitmq
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgA4zNNSmL3rPIkdwQF315WtNrUWzOJToDckk8uREbeoTLeg76A6/DKUHor3QpJYWdcZArUgtIUsXfcX2MVdf3+cAwIm/yqHISR4u7nztQHEV/zNMF8K6pCkwvIThbWZ3SaZMnx0OY/0no6V91hmGjX8wQpmo/Pj1Zz2LrcvKmMJdo1kCIn2eGr+gd6qykvW2lNBqc3LZY/jE3G8hvN4R/Fws7Q/rgVSCTVd0h+6m3Bo53UbmHyQO2Uxo8vVyiyATq1jWcHVdbeKDYTaLrJHUhNh2jOo3NEPqB/czHKUIJjdkYOtQqNPsFjI7M4sMgfgslRewjFKZDkq1Vw3PufqSj5hjy3bsbAqgWek7fO95sIzOeDBfk2xzb/1sFZAd/CBdLtGLWKeHVnQuKQ5AjLnSQAmZYYKQT9vTChqpUv9MZfDhjVJYxgt2cjjgbmaM115cSnXCaoj1Sf4BI+VKKk7Q+DLJmRGbYipeik35WK3muN/n+MWD8kzsyoCO2KkropSBk1lRI6g6bZ7aZByJh7Z2xiMOlhK4VK5xO60Gbw2+5CHhsLB/h14uqmJyg8F2gKFdttk8Rk/dub+GlVghYxLfoMeZm2QQvtLj7tdUc8NXoWFco3cSeqqATwQJi6+8svr6ef288/mnbAYwldgSHMF2DmTtUuDXpUG1solbDj7qNQV2N9kewRF3JfFq1YeENLi2NkA6vpdFUM6dJ0zSXSvZWrzeYw7Uqswr0DRUXSVamLMV0/C5XsewXzp
    RABBITMQ_DEFAULT_USER: AgATki1GVReh+dQ491t63djAo6fEJ3DUqzfAc4aXheDujINKpvlj3DsEtpXqv4Gr7Z47m3Dea2DQsDxSvwQB7Lwfghzt1YKMmblhWyPcdB4WIZDQ3PYRtJu1OCVbnalB0/lphryfHBEDrkHobZWp7+vT1YbfTmjaNRueoRorTvblyfa4l2CctEJUVu6JLZgK/Uh4ptwnxz/E0u3An0ZAAeQSf5PACFyLE/opbVfZBi8C/5ViDbhGmAzKGNyXYGVt7IJskeJLIyw34hn6yAMQmpmPr5HDd9J7stNd4z26oRqmzJYi6u53Y+aPQEB0PN4LvHey9mrCO8Lxvxr92H540ngpjM9wIIURmBI0S/eQiC8k5JRkAOHTUygSwCQ8cT7OPC7XPesv+iBUq68rCh+Z8bAASQka1V0MdrEfQg4lunWI6l/rgKl/hqVw+y0TLdGxDOO9P9kzWI3kg8ngD/7MQRcNzQq2479aYAOyUvEDixtuYVEZRge/AINiX3HhGsFsPQsVCpeqlB69cF6PyqJBcTY2BEEL06zoh3uGZ7m0auDR0NyhtIKznRYeY5FqDZN/hNBR6wB3x6PtxvOfbLybr7hH3vNZE8vEfZpnJmCuq6x93eHh8YSKAbbBUrr3IYviXEB/1WzYi6HI5YCzzs/QE7j1QNXDQLvZn2LSa/7RX/4LvSdv5eAtQP5d6owWr2adazuxoOxG6g==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: rabbitmq
    type: Opaque

