apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: default
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgBiztnf1pVhGNSwWkXjuuBBTki/T8vOfvXwQt4XW47JoP2eV0dCrVMYFJFIxcCcp6vBK2V5cMkDhPYAEjXeVaM5fSpXnUAfOA7E+BsSYfd+cIHclzgD2Lla5YHLh9pkS7krl5BJY3s92MHxuEtBMRqKazK2zrmd0R5rnsYQgfgtkNri4P8/pd3ZxkzJoFmEPslyxvAl0h7KLVWE7enlvZ8P7hNdApQ59/4nr1HaK8Oxi/Ze20QZSwHyWiirNiBRky9hhgsF9uEsMW/D2e/ViUqZ7OrPEZymAnTKg2xxWn8M6QYiGHPiT/JrHVDnX9T7iAvwrj60Y4tQZidFuhBSE88OzDWwu2ieW1t2HmMtMxAc3mGHrQ1tb9CtMnzr6LG/E2NhmlrdnNMzEclri3OR+vyJAOh21wsrIMW/w+e0nAyGinplx8IW2HH6Ynlf7aD8iDE71Tl0ehJkT+p23YzDlwUD8ZbAYVcI5O2JYJq50Wi7osQ2t2wGuZWyhfSs+M8UtJ/Pg+UOiEOlLVUlSc3ORuWAea7SVF45Hj4wPyK8IH6TQnelAUmMjDcTy4A88RNFnJwkSVuTjEMSVmgsiaQ2F1q7lHynDPlccgvnjOf8YLm11GtOPnhvlV9gYrMCg8ZNRaOypKH6i+3DO6FCMVxDZnk1R42aYhHd4Hkk7AcUCj4ec+QrMhWyFE6MsEs9bTx5Eli1PnNGl/pPuwZV5jQsDFKBEb5prQwRAFq8MpBshV16fnKljH3fKE0y
    RABBITMQ_DEFAULT_USER: AgAViMzmcInXgngl7/MT3xGe70BzVXLFYC2kwikd/7PefirkxYhoJkw/hFpYcdIDr9/I7Id10Chp8rWnSKNEft//x8+0pV+TswGiV73IWphljanuGAsaOXI4WqJfwm59dWneR+Olz+PGCrXeISvlHP8VPK5cRoBrtvKs0rPcaXt7ZCCcLmGgRYjwEGAgvZx//gUVqBXJZiqjB6vZ04UqOiv/iWkhB8Xw5ugrARqNgbDoMPVCI8xm/NTQ+RJZ7r2XfdOr7v8jfHjlbwzF3LGBpPdM73DcgqTlBpWHvWo/KfUf3Vk6StuFnPi1bzHt3VQv9DdibeMfOiMgMdqeJxN8w/AI/EkfOReyaXZzqg1tATmRJHkQ6OASoSAbl6FOq3ZWeNaeBYPt3s+c7LX6q5eAgrlizYupL0hv1ScxX/YgMNIIGPzvildgrKflcrrNzHsjxszwY7QbMmtPQpzGUEvJfH0k2Oj4kiMpP+kM9Z7his4uHetLJE3mEyycthKAefdrug+1U7rAtZFTqzo2F1uSdraq4UyJZWucPYW4hPXcKdEfu+w97J9dAkrhFBw64JgXeeYQWSforM/gAzXk+iWm7knIY/4NxEr2QnfHd0enBJFWNwWUolmeQCoKEdNciGAj2zcbH2wl80rX4+sg9rqgdaAEVIQfAwDjJZAoIN8mSDnRWnHtP/0n6W7PD+k5QR0kODWNNqGNIw==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: default
    type: Opaque

