apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
spec:
  selector:
    matchLabels:
      app: rabbitmq-depl
  template:
    metadata:
      labels:
        app: rabbitmq-depl
    spec:
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
            readOnly: false
      containers:
      - name: rabbitmq-depl
        image: rabbitmq:3.11-management
        resources:
          requests:
            cpu: 20m
            memory: "128Mi"
          limits:
            memory: "512Mi"
        volumeMounts:
          - name: rabbitmq-volume
            mountPath: /var/lib/rabbitmq
        envFrom:
         - secretRef: 
            name: rabbitmq-secret
            optional: true
        env:
          - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
            value: "-rabbit loopback_users none"
        ports:
        - containerPort: 15672
        - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ampq-srv
spec:
  selector:
    app: rabbitmq-depl
  ports:
  - port: 5672
    targetPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-srv
spec:
  selector:
    app: rabbitmq-depl
  ports:
  - port: 15672
    targetPort: 15672