apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-patient-api-depl
  namespace: backend-api
spec:
  selector:
    matchLabels:
      app: backend-patient-api-depl
  template:
    metadata:
      labels:
        app: backend-patient-api-depl
    spec:
      containers:
        - name: backend-patient-api-depl
          image: synthiatelemed.azurecr.io/backend-api:c0c7398f263709a6e4852fa608f2583c628e9c58
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "16Mi"
              cpu: "10m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-api-secret
            - configMapRef:
                name: backend-api-configmap
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
