
name: Backend API New Image

on:
  repository_dispatch:
    types: [doctor-frontend-new-image]
    
jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Doctor Frontend Image Tag
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i k8s/frontend/doctor/doctor-frontend-depl.yaml
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[BOT]: update image to ${{ github.event.client_payload.image }}"
